### ISSUE TITLE
Not threadsafe with sufficient load

### ISSUE THREAD

**Issue by Lamarth** [DiffSharp/DiffSharp#107]
Running 0.8.4 I get exceptions trying to run too much in different threads. This does not affect 0.7.7. 

```
open DiffSharp.AD.Float64;;
let sphere (xs:DV) = xs * xs;;
Array.Parallel.map (DV >> grad sphere) (Array.replicate 10000 (Array.replicate 3 1.));;
```

```
System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Unable to cast object of type 'D' to type 'DV'.
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 598
   at DiffSharp.AD.Float64.DOps.adjoint[T](Adjoints adjoints, T d)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@1317-3.Invoke(Int32 i) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\array.fs:line 1318
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map[T,TResult](FSharpFunc`2 mapping, T[] array) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\array.fs:line 1319
   at <StartupCode$FSI_0080>.$FSI_0080.main@()
---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'D' to type 'DV'.
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 598
   at DiffSharp.AD.Float64.DOps.adjoint[T](Adjoints adjoints, T d)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@1317-3.Invoke(Int32 i) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\array.fs:line 1318
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
```

My real scenario has a different stack trace, and reliably occurs with only 2 threads, but I imagine it has a similar cause:

```
The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DiffSharp.AD.Float64.Adjoints.ApplyDelta(Int32 uniq, Delta x)
   at DiffSharp.AD.Float64.DOps.pushRec@3592-8(Adjoints adjoints, Dictionary`2 fanouts, FSharpList`1 ds)
<my gradhessian' call>
```

**Comment by dsyme** [comment]
@Lamarth You're totally right and this is my fault. I made the change to use an Adjoints table in an incorrect attempt to achieve better immutability guarantees, but didn't correctly consider the concurrency aspect.

Things have move along a lot on the `dev` branch and the whole basis of DiffSHarp is changing.  If this is still an issue for you in practice I can work on a PR to adjust master back to the previous technique.

**Comment by Lamarth** [comment]
@dsyme Not a big deal - I just rolled back to 0.7.7, which suits my needs just as well as 0.8.4. So long as it doesn't impact the next release version I'm all happy. Thanks for all your work here and across F#, and I eagerly await the big new version of DiffSharp!
