### ISSUE TITLE
Scalar on GPU or setting config to Torch/GPU fails

### ISSUE THREAD

**Issue by kevmal** [DiffSharp/DiffSharp#271]
A first call to `dsharp.config(backend=Backend.Torch, device=Device.GPU)` fails with

```
System.InvalidOperationException: Torch device type CUDA did not initialise on the current machine.
   at TorchSharp.Torch.InitializeDeviceType(DeviceType deviceType)
   at TorchSharp.Tensor.TorchTensor.ToDevice(DeviceType deviceType, Int32 deviceIndex)
   ...
```

This is because 
https://github.com/DiffSharp/DiffSharp/blob/12137670a9aa347a0ac3199b45526c4118a821a7/src/DiffSharp.Core/DiffSharp.fs#L1116

Calls `Float64Tensor.From(0.)` 

https://github.com/xamarin/TorchSharp/blob/bffe20f1221d5e0f2985cef573f393e3c7187238/src/TorchSharp/Tensor/TorchTensorTyped.generated.cs#L2190-L2196

Initializing torch to `DeviceType.CPU` and committing to the "torch_cpu" library.

A workaround is to make sure GPU is the first used device:

```
dsharp.tensor(1f, Dtype.Float32, Device.GPU, Backend.Torch)
dsharp.config(backend=Backend.Torch, device=Device.GPU)
```
 Works fine because 
https://github.com/xamarin/TorchSharp/blob/bffe20f1221d5e0f2985cef573f393e3c7187238/src/TorchSharp/Tensor/TorchTensorTyped.tt#L259-L271

Does not first initialize device type.

Overall it looks like this was introduced in 
https://github.com/xamarin/TorchSharp/commit/7b3f3ca5c6233eb20010f231cab65178103eeae2

Where an initialization mask was swapped out for a single bool.

**Comment by dsyme** [comment]
@kevmal Thank you for reporting this

**Comment by gbaydin** [comment]
We've been investigating this with @dsyme and it led to the observations reported here https://github.com/dotnet/TorchSharp/issues/345

**Comment by gbaydin** [comment]
@kevmal recent changes merged in #378 incorporated your suggested fix here: https://github.com/DiffSharp/DiffSharp/pull/378/commits/2dbeb966daf5bfab8e92ee0013f85b71e990653b

In my system (Linux with libtorch 1.9.0) and latest DiffSharp I don't have any issues with a first call to `dsharp.config(backend=Backend.Torch, device=Device.GPU)` so I'm closing this issue. Please let me know if there's anything I missed and we can reopen the issue.

**Comment by gbaydin** [comment]
Also the recently merged #383 should significantly improve the reliability of loading native components as TorchSharp and libtorch native libraries are packaged together which helps them to be found together in runtime.

**Comment by dsyme** [comment]
Note that even after #383 the package restore will not yet unify native binaries into a single place that's fully auto-loadable from F# interactive and notebooks. Hence there is still the workaround code in torchsharp to facilitate the loading. It works but feels fragile and is not under CI automated test, I wouldn't be surprised if we end up back here.
