### ISSUE TITLE
Batch matmul fails for Torch backend

### ISSUE THREAD

**Issue by gbaydin** [DiffSharp/DiffSharp#355]
I noticed that the batched matrix multiplication fails with the torch backend. It seems that we assume libtorch matmul should handle that batched matmul, but it doesn't. I think we need to call libtorch `bmm` instead to support this case.

Example that works fine with reference backend but fails with torch backend.

```fsharp
dsharp.config(backend=Backend.Torch, device=Device.CPU)

let a = dsharp.randn([2; 10; 10])
let b = dsharp.randn([2; 10; 10])
let c = a.matmul(b)

print a.shape
print b.shape
print c.shape
```

```
System.Runtime.InteropServices.ExternalException (0x80004005): self must be a matrix
Exception raised from mm_cpu_out at /pytorch/aten/src/ATen/native/LinearAlgebra.cpp:1112 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fc1c6c7aa22 in /home/gunes/anaconda3/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x5f (0x7fc1c6c774af in /home/gunes/anaconda3/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: at::native::mm_cpu_out(at::Tensor const&, at::Tensor const&, at::Tensor&) + 0x17f (0x7fc0cd7dbb6f in /home/gunes/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: at::native::mm_cpu(at::Tensor const&, at::Tensor const&) + 0x7d (0x7fc0cd7dbc4d in /home/gunes/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x1a12fef (0x7fc0ce0cefef in /home/gunes/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x183d299 (0x7fc0cdef9299 in /home/gunes/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: at::redispatch::mm(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&) + 0x5b (0x7fc0cdefbb8b in /home/gunes/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x3131a3a (0x7fc0cf7eda3a in /home/gunes/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x3132192 (0x7fc0cf7ee192 in /home/gunes/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: at::Tensor::mm(at::Tensor const&) const + 0x125 (0x7fc0ce39ea95 in /home/gunes/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #10: THSTensor_mm + 0x51 (0x7fc1c67503e1 in /home/gunes/git/github/DiffSharp/DiffSharp/./examples/../tests/DiffSharp.Tests/bin/Debug/net5.0/runtimes/linux-x64/native/libLibTorchSharp.so)
frame #11: [0x7fc1cc2ebb64]

   at TorchSharp.Torch.CheckForErrors()
   at TorchSharp.Tensor.TorchTensor.mm(TorchTensor target)
   at DiffSharp.Backends.Torch.TorchRawTensor.MatMulTT(RawTensor t2) in /home/gunes/git/github/DiffSharp/DiffSharp/src/DiffSharp.Backends.Torch/Torch.RawTensor.fs:line 631
   at <StartupCode$DiffSharp-Core>.$Tensor.matmul@1295.Invoke(Tuple`2 tupledArg) in /home/gunes/git/github/DiffSharp/DiffSharp/src/DiffSharp.Core/Tensor.fs:line 1295
   at DiffSharp.Tensor.matmul(Tensor b) in /home/gunes/git/github/DiffSharp/DiffSharp/src/DiffSharp.Core/Tensor.fs:line 1295
   at <StartupCode$FSI_0001>.$FSI_0001.main@()
Stopped due to error
```

**Comment by gbaydin** [comment]
We didn't catch this before because the corresponding tests were using the reference backend only.
