### ISSUE TITLE
Problem with package refs?

### ISSUE THREAD

**Issue by gbaydin** [DiffSharp/DiffSharp#387]
I'm trying to run a simple F# script on a new machine with a clean install of dotnet in linux.

```
dotnet --version
6.0.100-rc.2.21505.57
```

Script content:
```fsharp
#!/usr/bin/env -S dotnet fsi
#r "nuget: DiffSharp-cpu, 1.0.0-preview-1338129467"

open DiffSharp
dsharp.config(dtype=Dtype.Float32,device=Device.CPU,backend=Backend.Torch)
let x0 = dsharp.tensor([3.5, 1.5])
```

I was thinking that the recent updates to TorchSharp #383 and https://github.com/dotnet/TorchSharp/pull/387 would mean that a simple inclusion of `#r "nuget: DiffSharp-cpu, 1.0.0-preview-1338129467"` would be enough for the script to run because 
* [DiffSharp-cpu 1.0.0-preview-1338129467](https://www.nuget.org/packages/DiffSharp-cpu/1.0.0-preview-1338129467) references
* [TorchSharp-cpu 0.93.5](https://www.nuget.org/packages/TorchSharp-cpu/0.93.5) and this references
* [libtorch-cpu 1.9.0.11](https://www.nuget.org/packages/libtorch-cpu/1.9.0.11)

which should make everyting nicely restored and ready to run.

But the script gives me the following output:

```
This application uses TorchSharp but doesn't contain reference to either libtorch-cuda-11.1-linux-x64 or libtorch-cpu, 1.9.0.11. Consider either referencing one of these packages or call System.Runtime.InteropServices.NativeLibrary.Load(path-to-libLibTorchSharp.so) explicitly for a Python install or a download of libtorch.so/torch.dll. See https://github.com/dotnet/TorchSharp/issues/169.". Trace from LoadNativeBackend:

TorchSharp: LoadNativeBackend: Initialising native backend, useCudaBackend = False

Step 1 - First try regular load of native libtorch binaries.

    Trying to load native component torch_cpu relative to /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/TorchSharp.dll
    Trying to load native component LibTorchSharp relative to /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/TorchSharp.dll
    Failed to load native component LibTorchSharp relative to /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/TorchSharp.dll
    Result from regular native load of LibTorchSharp is False

Step 3 - Alternative load from consolidated directory of native binaries from nuget packages

    torchsharpLoc = /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1
    packagesDir = /home/gunes/.nuget/packages
    torchsharpHome = /home/gunes/.nuget/packages/torchsharp/0.93.5
    Trying dynamic load for .NET/F# Interactive by consolidating native libtorch-cpu-* binaries to /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/cpu...
    Consolidating native binaries, packagesDir=/home/gunes/.nuget/packages, packagePattern=libtorch-cpu, packageVersion=1.9.0.11 to target=/home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/cpu...
    CopyNativeComponentsIntoSingleDirectory: natives=/home/gunes/.nuget/packages/libtorch-cpu/1.9.0.11/runtimes/linux-x64/native
    Consolidating native binaries, packagesDir=/home/gunes/.nuget/packages, packagePattern=torchsharp, packageVersion=0.93.5 to target=/home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/cpu...
    CopyNativeComponentsIntoSingleDirectory: natives=/home/gunes/.nuget/packages/torchsharp/0.93.5/runtimes/linux-x64/native
    Trying to load native component /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/cpu/libLibTorchSharp.so
    Failed to load native component /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/cpu/libLibTorchSharp.so

System.NotSupportedException: This application uses TorchSharp but doesn't contain reference to either libtorch-cuda-11.1-linux-x64 or libtorch-cpu, 1.9.0.11. Consider either referencing one of these packages or call System.Runtime.InteropServices.NativeLibrary.Load(path-to-libLibTorchSharp.so) explicitly for a Python install or a download of libtorch.so/torch.dll. See https://github.com/dotnet/TorchSharp/issues/169.". Trace from LoadNativeBackend:

TorchSharp: LoadNativeBackend: Initialising native backend, useCudaBackend = False

Step 1 - First try regular load of native libtorch binaries.

    Trying to load native component torch_cpu relative to /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/TorchSharp.dll
    Trying to load native component LibTorchSharp relative to /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/TorchSharp.dll
    Failed to load native component LibTorchSharp relative to /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/TorchSharp.dll
    Result from regular native load of LibTorchSharp is False

Step 3 - Alternative load from consolidated directory of native binaries from nuget packages

    torchsharpLoc = /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1
    packagesDir = /home/gunes/.nuget/packages
    torchsharpHome = /home/gunes/.nuget/packages/torchsharp/0.93.5
    Trying dynamic load for .NET/F# Interactive by consolidating native libtorch-cpu-* binaries to /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/cpu...
    Consolidating native binaries, packagesDir=/home/gunes/.nuget/packages, packagePattern=libtorch-cpu, packageVersion=1.9.0.11 to target=/home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/cpu...
    CopyNativeComponentsIntoSingleDirectory: natives=/home/gunes/.nuget/packages/libtorch-cpu/1.9.0.11/runtimes/linux-x64/native
    Consolidating native binaries, packagesDir=/home/gunes/.nuget/packages, packagePattern=torchsharp, packageVersion=0.93.5 to target=/home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/cpu...
    CopyNativeComponentsIntoSingleDirectory: natives=/home/gunes/.nuget/packages/torchsharp/0.93.5/runtimes/linux-x64/native
    Trying to load native component /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/cpu/libLibTorchSharp.so
    Failed to load native component /home/gunes/.nuget/packages/torchsharp/0.93.5/lib/netcoreapp3.1/cpu/libLibTorchSharp.so

   at TorchSharp.torch.LoadNativeBackend(Boolean useCudaBackend, StringBuilder& trace)
   at TorchSharp.torch.InitializeDeviceType(DeviceType deviceType)
   at TorchSharp.torch.tensor(IList`1 rawArray, Int64[] dimensions, Nullable`1 dtype, Device device, Boolean requiresGrad)
   at <StartupCode$DiffSharp-Backends-Torch>.$Torch.RawTensor.-ctor@1232-2.Invoke(Tuple`2 tupledArg)
   at DiffSharp.Backends.Torch.TorchTensorOps`2.CreateFromFlatArray(Array values, Int32[] shape, Device device)
   at DiffSharp.Backends.Torch.TorchBackendTensorStatics.CreateFromFlatArray(Array values, Int32[] shape, Dtype dtype, Device device)
   at DiffSharp.Tensor.create(Object value, FSharpOption`1 device, FSharpOption`1 dtype, FSharpOption`1 backend)
   at DiffSharp.dsharp.config(FSharpOption`1 device, FSharpOption`1 dtype, FSharpOption`1 backend, FSharpOption`1 printer)
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error

```

**Comment by dsyme** [comment]
I have a fix in the works for this - and am also able to repro it on Windows

I will add a test here of some kind so we find this a bit earlier (when upgrading TorchSharp packages).  It's hard to test in TorchSharp CI
