### ISSUE TITLE
Strange error regarding "HIP" backend

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#403]
I just got this strange error running in updated examples/vae.fsx

Code:
```
#I "../tests/DiffSharp.Tests/bin/Debug/net5.0"
#r "DiffSharp.Core.dll"
#r "DiffSharp.Data.dll"
#r "DiffSharp.Backends.Torch.dll"
#r "nuget: TorchSharp-cpu, 0.96.0"
...
<rest of vae.fsx>
printfn "Model\n%s" (model.summary())
```

```
> 
System.Runtime.InteropServices.ExternalException (0x80004005): Could not run 'aten::empty.memory_format' with arguments from the 'HIP' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty.memory_format' is only available for these backends: [CPU, Meta, MkldnnCPU, SparseCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at aten\src\ATen\RegisterCPU.cpp:16286 [kernel]
Meta: registered at aten\src\ATen\RegisterMeta.cpp:9460 [kernel]
MkldnnCPU: registered at aten\src\ATen\RegisterMkldnnCPU.cpp:563 [kernel]
SparseCPU: registered at aten\src\ATen\RegisterSparseCPU.cpp:959 [kernel]
BackendSelect: registered at aten\src\ATen\RegisterBackendSelect.cpp:609 [kernel]
Named: registered at ..\..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\..\aten\src\ATen\core\VariableFallbackKernel.cpp:60 [backend fallback]
AutogradOther: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
AutogradCPU: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
AutogradCUDA: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
AutogradXLA: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
AutogradMLC: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
AutogradHPU: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
AutogradNestedTensor: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
AutogradPrivateUse1: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
AutogradPrivateUse2: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
AutogradPrivateUse3: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:9226 [autograd kernel]
Tracer: registered at ..\..\torch\csrc\autograd\generated\TraceType_4.cpp:9909 [kernel]
Autocast: fallthrough registered at ..\..\aten\src\ATen\autocast_mode.cpp:255 [backend fallback]
Batched: registered at ..\..\aten\src\ATen\BatchingRegistrations.cpp:1019 [backend fallback]
VmapMode: fallthrough registered at ..\..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]

Exception raised from reportError at ..\..\aten\src\ATen\core\dispatch\OperatorEntry.cpp:399 (most recent call first):
00007FFEB29C10D200007FFEB29C1070 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFEB29943C500007FFEB2994350 c10.dll!c10::NotImplementedError::NotImplementedError [<unknown file> @ <unknown line number>]
00007FFDBDEEEEA100007FFDBDEEECD0 torch_cpu.DLL!c10::impl::OperatorEntry::reportError [<unknown file> @ <unknown line number>]
00007FFDBE6CD2BA00007FFDBE692450 torch_cpu.DLL!at::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBE84EEB800007FFDBE839020 torch_cpu.DLL!at::redispatch::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBE84D25900007FFDBE839020 torch_cpu.DLL!at::redispatch::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBE53366A00007FFDBE533440 torch_cpu.DLL!at::empty [<unknown file> @ <unknown line number>]
00007FFDBE17478400007FFDBE1746B0 torch_cpu.DLL!at::native::randn [<unknown file> @ <unknown line number>]
00007FFDBE17492900007FFDBE1748C0 torch_cpu.DLL!at::native::randn [<unknown file> @ <unknown line number>]
00007FFDBEA7605A00007FFDBE839020 torch_cpu.DLL!at::redispatch::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBEA66E4600007FFDBE839020 torch_cpu.DLL!at::redispatch::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBE6CCEFD00007FFDBE692450 torch_cpu.DLL!at::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBE85362B00007FFDBE839020 torch_cpu.DLL!at::redispatch::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBE84CFC600007FFDBE839020 torch_cpu.DLL!at::redispatch::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBE61C10700007FFDBE61BF10 torch_cpu.DLL!at::randn [<unknown file> @ <unknown line number>]
00007FFE93D1C5B500007FFE93D1C450 LibTorchSharp.DLL!THSTensor_randn [<unknown file> @ <unknown line number>]
00007FFD95428847 <unknown symbol address> !<unknown symbol> [<unknown file> @ <unknown line number>]

   at TorchSharp.torch.CheckForErrors()
   at TorchSharp.torch.randn(Int64[] size, Nullable`1 dtype, Device device, Boolean requiresGrad, Generator generator)
   at <StartupCode$DiffSharp-Backends-Torch>.$Torch.RawTensor.-ctor@1251-15.Invoke(Tuple`2 tupledArg) in C:\GitHub\dsyme\DiffSharp\src\DiffSharp.Backends.Torch\Torch.RawTensor.fs:line 1251
   at DiffSharp.Backends.Torch.TorchTensorOps`2.RandomNormal(Int32[] shape, Device device) in C:\GitHub\dsyme\DiffSharp\src\DiffSharp.Backends.Torch\Torch.RawTensor.fs:line 1223
   at DiffSharp.Backends.Torch.TorchBackendTensorStatics.RandomNormal(Int32[] shape, Dtype dtype, Device device) in C:\GitHub\dsyme\DiffSharp\src\DiffSharp.Backends.Torch\Torch.RawTensor.fs:line 1546
   at DiffSharp.Backends.RawTensor.RandomNormal(Int32[] shape, FSharpOption`1 dtype, FSharpOption`1 device, FSharpOption`1 backend) in C:\GitHub\dsyme\DiffSharp\src\DiffSharp.Core\RawTensor.fs:line 168
   at DiffSharp.dsharp.randn(IEnumerable`1 shape, FSharpOption`1 device, FSharpOption`1 dtype, FSharpOption`1 backend) in C:\GitHub\dsyme\DiffSharp\src\DiffSharp.Core\DiffSharp.fs:line 295
   at DiffSharp.Model.Weight.kaiming(Int32 fanIn, Int32 fanOut, FSharpOption`1 a) in C:\GitHub\dsyme\DiffSharp\src\DiffSharp.Core\Model.fs:line 557
   at DiffSharp.Model.Linear..ctor(Int32 inFeatures, Int32 outFeatures, FSharpOption`1 bias) in C:\GitHub\dsyme\DiffSharp\src\DiffSharp.Core\Model.Linear.fs:line 14
   at FSI_0004.VAE..ctor(Int32 xDim, Int32 zDim, FSharpOption`1 hDims, FSharpOption`1 nonlinearity, FSharpOption`1 nonlinearityLast)
   at <StartupCode$FSI_0010>.$FSI_0010.main@()
Stopped due to error
```

**Comment by dsyme** [comment]
I've verified this didn't happen with TorchSHarp 0.93.5 - I'm going to revert the update to 0.96.0 until we work out what's going on.
