### ISSUE TITLE
In the rnn.fsx example, languageModel.summary() throws an error after the model has been trained.

### ISSUE THREAD

**Issue by nhirschey** [DiffSharp/DiffSharp#421]
If I run the rnn.fsx example and try to run languageModel.summary() after the training loop, I get this exception
```fsharp
> languageModel.summary()
System.Exception: Cannot cat tensors with different differentiation type (TensorC, TensorF, TensorR).
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at DiffSharp.Tensor.cat(IEnumerable`1 tensors, FSharpOption`1 dim)
   at DiffSharp.Model.ParameterDict.flatten()
   at DiffSharp.Model.ModelBase.summary()
   at <StartupCode$FSI_0014>.$FSI_0014.main@()
Stopped due to error
> 
```

This seems to be caused by `languageModel.buffers` being in reverseDiff mode. If I make the buffers nodiff summary works.
```fsharp
languageModel.state.isNoDiff // true
languageModel.parameters.isNoDiff //true
languageModel.buffers.isNoDiff  //false
languageModel.buffers.isReverseDiff  //true

languageModel.buffers.noDiff() // ()
languageModel.buffers.isNoDiff // true
languageModel.summary()
(*
  "---
Model                                              Params
---
RNNCell(65, 512)                                  295,936
RNNCell(512, 512)                                 524,800
Linear(512, 65)                                    33,345
---
Total params                  : 870,465
Trainable params              : 854,081
Non-trainable params (buffers): 16,384
---
Total params size (MiB)       : 3.32
---
"
*)
```

**Comment by gbaydin** [comment]
It should be fixed in #425. Please let me know if the problem persists.
